//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapevine.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrapevineEntities : DbContext
    {
        public GrapevineEntities()
            : base("name=GrapevineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Categories> tbl_Categories { get; set; }
        public DbSet<tbl_Cities> tbl_Cities { get; set; }
        public DbSet<tbl_Contacts> tbl_Contacts { get; set; }
        public DbSet<tbl_Countries> tbl_Countries { get; set; }
        public DbSet<tbl_States> tbl_States { get; set; }
        public DbSet<tbl_UserConnections> tbl_UserConnections { get; set; }
        public DbSet<tbl_UserImages> tbl_UserImages { get; set; }
        public DbSet<tbl_UserNotifications> tbl_UserNotifications { get; set; }
        public DbSet<tbl_UserReviews> tbl_UserReviews { get; set; }
        public DbSet<tbl_Users> tbl_Users { get; set; }
    }
}
