//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapevine.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cities
    {
        public int iCityId { get; set; }
        public string vCity { get; set; }
        public string vCode { get; set; }
        public Nullable<int> iCountryId { get; set; }
        public Nullable<int> iStateId { get; set; }
    }
}
