//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapevine.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public int iUserId { get; set; }
        public string vName { get; set; }
        public string vEmail { get; set; }
        public string vPassword { get; set; }
        public string vCountryCodeMobile { get; set; }
        public string vMobile { get; set; }
        public string vAddress1 { get; set; }
        public string vAddress2 { get; set; }
        public string vCity { get; set; }
        public string vState { get; set; }
        public string vCountry { get; set; }
        public Nullable<int> iCityId { get; set; }
        public Nullable<int> iStateId { get; set; }
        public Nullable<int> iCountryId { get; set; }
        public string vCompName { get; set; }
        public Nullable<int> iCategoryId { get; set; }
        public string vWebsite { get; set; }
        public string vAboutMe { get; set; }
        public string vVerifyCode { get; set; }
        public string vImgUrl { get; set; }
        public Nullable<bool> bStatus { get; set; }
        public Nullable<System.DateTime> dCreateDate { get; set; }
        public Nullable<System.DateTime> dUpdateDate { get; set; }
        public string vLatitude { get; set; }
        public string vLongitude { get; set; }
        public string vDeviceId { get; set; }
        public string facebookId { get; set; }
        public string twitterId { get; set; }
    }
}
