//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapevine.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Categories
    {
        public int iCategoryId { get; set; }
        public string vCatName { get; set; }
        public string vImgUrl { get; set; }
        public string vDescription { get; set; }
        public Nullable<bool> bStatus { get; set; }
    }
}
