//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapevine.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserReviews
    {
        public int iUserReviewId { get; set; }
        public Nullable<int> iUserId { get; set; }
        public Nullable<int> iReviewById { get; set; }
        public string vDesc { get; set; }
        public Nullable<System.DateTime> dReviewDate { get; set; }
        public Nullable<double> vOverRate { get; set; }
    }
}
